### ISSUE TITLE
Error: Cannot find module 'opentype'

### ISSUE THREAD

**Issue by kovart** [bramstein/opentype#12]
opentype has been installed, but node throws an error when I try to perform javascript file with "var parse = require('opentype')".

**Comment by nicematt** [comment]
If you want to use opentype in browser javascript you can include this one I found on http://opentype.js.org/dist/opentype.js.

**Comment by andy-ms** [comment]
`opentype` does not define an `index.js` or a package.json `main` entry, so I can't import it.
I also can't import `opentype/src/opentype.js` since it uses the `goog` global variable, which isn't available by default in node.
It also wouldn't work if I did `require("google-closure-library")` before `require("opentype/src/opentype.js")`, because I get `Error: goog.require could not find: opentype.Format`.

@nicematt That is a different package; `opentype.js` and `opentype` are not the same.

**Comment by nicematt** [comment]
@andy-ms Yes, this opentype.js I quoted is for web browsers. Maybe yours problem is cause of format.js?

**Comment by kennethormandy** [comment]
Hey, the issue you are having is probably becuase latest version tagged version on npm (v0.1.2) didn’t have CommonJS support, and another one hasn’t been published with all the updates in the master branch.

Here’s how you can get around that in the meantime. Install the latest tag from GitHub instead of the npm package:

```sh
npm uninstall --save opentype
npm install --save https://github.com/bramstein/opentype
```

npm will turn this into a specific commit and hash so you are still installing something specific at least. Then, in your JS file:

```js
var opentype = require('opentype/src/opentype.js')
```
